env:
  global:
  - secure: LBTN8d1hS7ocrqDwxLQqU0tfK3FMCXBI8q1yASEjtkp/v5HEyFkbj22H4jXZ20SkpCTlIG2L6i/fU3d6KzJUzTFuxkQEWsnjkj4jAhxGEWRsT1RV6VcUPQDGLHapXwTy+ZYgMNxE7aAdQaBskPHdVzAhjrzlTwVuKp6KjFn+kMU=
  - secure: oXHfetR+eH/Z/eqSRolCDyTqT8KLpdP7xnseGOJaok6V+GfIOrJ7E73hqVqS3aJoDlafvt4vyv9+joCgPo1I5WgJ602CNXQnOhQSnOOovaszgFr0htDLxqJUUg0+KP1O956J4c0XcmYd1YtvbOhmRIShGc/hUbp600QrKmVyif0=
matrix:
  include:
  - os: osx
    osx_image: xcode8
    language: objective-c
    compiler: clang
    env: NAME="osx" SCRIPT_PATH="scripts/$NAME" SCRIPT="$SCRIPT_PATH/buildPG.sh"
script: "$SCRIPT"
git:
  depth: 10
